### ISSUE TITLE
add this module in OCA

### ISSUE THREAD

**Issue by EBII** [leblanc-simon/odoo-attachment-preview#3]
Hello i use your module for a client. 
I prefer use OCA module for maintained version.

did you allow to add this module in OCA repositiory with a new PR for 10? 
already exist but different
https://github.com/OCA/knowledge/tree/8.0/attachment_preview
regards 
E.

**Comment by leblanc-simon** [comment]
No problem to add this module in OCA repository if ... you (or somebody other than me :)) create the pull request.
I've created this module only because my company use Odoo and each day I raged because I don't see the attachment :) and I don't want maintain it (Python or Odoo are not my core business)
